SOURCES=db/builder.cc db/c.cc db/db_impl.cc db/db_iter.cc db/dbformat.cc db/dbrotx.cc db/dbtables.cc db/dbtransaction.cc db/dbtx.cc db/delset.cc db/epoch.cc db/filename.cc db/gcqueue.cc db/hashtable.cc db/log_reader.cc db/log_writer.cc db/memtable.cc db/nodebuf.cc db/objpool.cc db/rcu.cc db/repair.cc db/rmpool.cc db/rmqueue.cc db/table_cache.cc db/txleveldb.cc db/txskiplist.cc db/version_edit.cc db/version_set.cc db/write_batch.cc lockfreememstore/lockfree_hash.cc memstore/memstore_bplustree.cc memstore/memstore_cuckoohash.cc memstore/memstore_eunotree.cc memstore/memstore_hash.cc memstore/memstore_simple.cc memstore/memstore_skiplist.cc memstore/memstore_stringbplustree.cc memstore/memstore_uint64bplustree.cc memstore/secondindex_stringbplustree.cc memstore/secondindex_uint64bplustree.cc persistent/log.cc persistent/pbuf.cc persistent/tbuf.cc silo_benchmark/articles.cc silo_benchmark/bench.cc silo_benchmark/thread.cc silo_benchmark/tpcc.cc silo_benchmark/varint.cc table/block.cc table/block_builder.cc table/filter_block.cc table/format.cc table/iterator.cc table/merger.cc table/table.cc table/table_builder.cc table/two_level_iterator.cc tpcc/clock.cc tpcc/randomgenerator.cc tpcc/stupidunit.cc tpcc/tpccclient.cc tpcc/tpccdb.cc tpcc/tpccgenerator.cc tpcc/tpccleveldb.cc tpcc/tpccskiplist.cc tpcc/tpcctables.cc tpcc/tpcctxmemstore.cc util/arena.cc util/bloom.cc util/bloomfilter.cc util/cache.cc util/coding.cc util/comparator.cc util/crc32c.cc util/env.cc util/env_posix.cc util/filter_policy.cc util/hash.cc util/histogram.cc util/logging.cc util/murmurhash.cc util/options.cc util/rtm.cc util/rtm_arena.cc util/rwlock.cc util/status.cc  port/port_posix.cc
MEMENV_SOURCES=helpers/memenv/memenv.cc
CC=gcc-4.8
CXX=g++-4.8
PLATFORM=OS_LINUX
PLATFORM_LDFLAGS=-pthread -mrtm
PLATFORM_LIBS= -lsnappy -lssmalloc
PLATFORM_CCFLAGS=  -pthread -DOS_LINUX -mrtm -DLEVELDB_PLATFORM_POSIX -DSNAPPY
PLATFORM_CXXFLAGS=  -pthread -DOS_LINUX -mrtm -DLEVELDB_PLATFORM_POSIX -DSNAPPY
PLATFORM_SHARED_CFLAGS=-fPIC
PLATFORM_SHARED_EXT=so
PLATFORM_SHARED_LDFLAGS=-shared -Wl,-soname -Wl,
PLATFORM_SHARED_VERSIONED=true
